### ISSUE TITLE
投稿作成ページの下余白をもう少し大きくしたい

### ISSUE THREAD

**Issue by toyoshin5** [toyoshin5/gohan_map#30]
<img width="538" alt="スクリーンショット 2023-07-04 22 42 05" src="https://github.com/toyoshin5/gohan_map/assets/43494392/70bf8d04-d94c-4ebf-8ab0-890e50d8623c">

コメント欄がキーボードに隠されてしまう
コメント欄が見えるところまでスクロールできるようにしてほしい

**Comment by karintou8710** [comment]
単純に余白増やすだけだと、通常時に無駄に空欄が出来るから良い方法ないかな。
