### ISSUE TITLE
現在位置に画像を配置したい

### ISSUE THREAD

**Issue by toyoshin5** [toyoshin5/gohan_map#31]
![blue_dot](https://github.com/toyoshin5/gohan_map/assets/43494392/7b6adfd4-56f8-452a-8b89-c628668cae9f)
 
これを現在位置に配置して欲しい

**Comment by karintou8710** [comment]
向いている方向の取得、常に最新位置の更新まで頑張れば出来る可能性あり
https://zenn.dev/ekito_station/articles/compass-flutter

**Comment by toyoshin5** [comment]
やろうと思えばできそうだね

**Comment by toyoshin5** [comment]
現在地のアイコン、MapPage()のpinに含めるとか、AppMap()に直接実装とか、実装する方法色々あると思うけど、AppMap()に直接実装するのが簡単かな〜
MapPageには現在地取得の関数書きたくないし

**Comment by karintou8710** [comment]
ステートとして現在地のアイコンを持って、それをpinsに入れた実装にした〜
MapPageには入れたくないね。

**Comment by toyoshin5** [comment]
自分もそれがいいと思う！あざす〜〜
