### ISSUE TITLE
マップ拡大と同時に回転してしまう

### ISSUE THREAD

**Issue by karintou8710** [toyoshin5/gohan_map#35]
２本指でピンチイン、ピンチアウトすると回転してしまうので、とりあえず回転をOFFにしても良さそう

**Comment by toyoshin5** [comment]
向きを固定して拡大縮小することが難しいってこと?
確かにテキストが回転してくれないので北が上で固定しちゃってもいいかもね

**Comment by toyoshin5** [comment]
ちなみにFlutterMapのMapOptionで
`enableMultiFingerGestureRace: true,`
を追加すると、回転と拡大縮小を同時にできなくなるらしい。試してみてもいいかも、

```
//flutter_map.dart
this.rotationThreshold = 20.0,
this.rotationWinGestures = MultiFingerGesture.rotate,
this.pinchZoomThreshold = 0.5,
this.pinchZoomWinGestures =
    MultiFingerGesture.pinchZoom | MultiFingerGesture.pinchMove,
this.pinchMoveThreshold = 40.0,
this.pinchMoveWinGestures =
        MultiFingerGesture.pinchZoom | MultiFingerGesture.pinchMove,
```

この辺で、回転or拡大縮小の判定基準を色々調整できるみたい

**Comment by karintou8710** [comment]
おお、それは知らなかった。
InteractiveFlagからrotate削除して対応しようとしたけど、試してみる。
あと、拡大中に上下左右移動するのも対応したい気持ち。

**Comment by toyoshin5** [comment]
よろしく！！
拡大中に上下左右移動ってどういうイメージ?

**Comment by karintou8710** [comment]
拡大中にマップ自体か移動しちゃう現象のこと〜
`enableMultiFingerGestureRace: true`にしたら全部直った！サンクス。
