### ISSUE TITLE
HapticFeedbackを取り入れたい

### ISSUE THREAD

**Issue by toyoshin5** [toyoshin5/gohan_map#48]
重要な操作を完了したタイミングで振動を実行させたい

### 必要ライブラリ
service(標準ライブラリ)&[flutter_haptic](https://pub.dev/packages/flutter_haptic)

標準ライブラリ:HapticFeedbackで単発の振動を実行
flutter_haptic:Hapticで複雑な振動を実行

### 実装してほしいタイミング
- マップを長押ししたとき
  - HapticFeedback.mediumImpact();
- 飲食店を追加,編集したとき
  - Haptic.onSuccess();
- 投稿を追加,編集したとき
  - Haptic.onSuccess();

**Comment by karintou8710** [comment]
振動、ネイティブアプリっぽい
