### ISSUE TITLE
一目でピンが指している店の知るために、ピンの種類を増やしたい

### ISSUE THREAD

**Issue by karintou8710** [toyoshin5/gohan_map#52]
全て同じピンだと一目で分かりずらいと感じた。
ラーメン、カフェ、居酒屋、ファミレス、ハンバーガーなど多くのピンを作成して選択可能にするのはどうだろうか。

イメージ => ロケスマアプリ
https://www.locationsmart.org/?tag=_all&lat=39.30989&lon=139.30474&z=6

**Comment by toyoshin5** [comment]
めっちゃあり！
GoogleMap,AppleMapみたいにピンの左に店名を置いたりすることもできそうだけど、それもどうだろう？

**Comment by karintou8710** [comment]
それも良さそう！ぱっと見でなんの店かわかるようにしたいね。

**Comment by toyoshin5** [comment]
ピンのデザイン案をここで募集します

**Comment by karintou8710** [comment]
このピンの白い空白部分に各料理カテゴリのアイコンを入れる
![image](https://github.com/toyoshin5/gohan_map/assets/80200187/2466e55e-ba5f-4a6e-b5c5-5a4dde6c5092)
