### ISSUE TITLE
全ての投稿一覧を眺めるページが欲しい

### ISSUE THREAD

**Issue by karintou8710** [toyoshin5/gohan_map#54]
現状だとお店ごとのタイムラインしか見れないので、全ての投稿を同時に確認できる手段がない

**Comment by toyoshin5** [comment]
確かに、一覧でみたいときもあるよね〜

**Comment by toyoshin5** [comment]
全投稿一覧は全画面で見たい、そしてできるだけ動作が軽くあるべきな気がして、
モーダル表示ではなくできれば普通にpush遷移したい..

**Comment by karintou8710** [comment]
これはワイも同じこと思ってた。
今後別のページも増えることを考えると、下部にナビゲーションバーつけるのありかも？

こんな感じの
![image](https://github.com/toyoshin5/gohan_map/assets/80200187/297faea7-db0f-441b-af43-6eec87cca9f7)

**Comment by toyoshin5** [comment]
ありだね〜〜
ただ、BottomNavigationBarをつけるだけだと、ModalがBottomNavigationBarの上に来てしまうから、
タブの中でモーダルを出そうと思うと実装が結構めんどくさい?ていうか無理かも

**Comment by toyoshin5** [comment]
<img width="200" alt="スクリーンショット 2023-08-16 2 27 36" src="https://github.com/toyoshin5/gohan_map/assets/43494392/6cf2f25d-8f16-4270-b999-9ddcf9ee440f">

<img width="200" alt="スクリーンショット 2023-08-16 2 27 40" src="https://github.com/toyoshin5/gohan_map/assets/43494392/bff0198f-a00a-41f9-9845-aa84474b5c6a">

**Comment by toyoshin5** [comment]
BottomNavigationBarをつけるなら、画面下部に検索バーを置くっていうデザインはどうしても破綻しちゃうよね。
どうしようか〜
