### ISSUE TITLE
新規登録時に飲食店の検索機能を実装する

### ISSUE THREAD

**Issue by karintou8710** [toyoshin5/gohan_map#58]
## 概要
試用で触っている感じ、過去に行った店の登録が非常に面倒だった。
以下の問題点があるように思える
- お店の位置をマップ上で正確に覚えていない
- マップ上に飲食店情報が表示されないので分かりずらい
- そこまでマップを移動するのが大変

## 解決策
実装が大変そうだが、登録時にお店の大雑把な名前から正確な名前、住所などを自動で入力する検索機能があると便利。
Google Mapみたいなもの（Gooogle Map使うのが早いというのはある)
flutter_mapでやるのであれば、飲食店情報を提供しているAPIを探すことになりそう。

**Comment by toyoshin5** [comment]
確かに、新規店舗も検索できると嬉しいなあ。そういうAPIあるかなあ

**Comment by toyoshin5** [comment]
対応完了なのでCloseします
