### ISSUE TITLE
画像読み込みの最適化

### ISSUE THREAD

**Issue by karintou8710** [toyoshin5/gohan_map#71]
タイムラインページで多く投稿されている際に、読み込み時間がかかる。
恐らく写真のサイズが大きいことが深く関わっていそう。

参考
https://read.pixelapps.io/save-99-cpu-memory-by-optimizing-images-in-your-flutter-app-prevent-crashes-77780669fa58

**Comment by toyoshin5** [comment]
Base64で直接保存するのをやめるor画像を圧縮するのがいいのかな
現状写真のプレビュー画面とかは無いので、結構圧縮してしまって良さそう
長辺1280pxの品質83%jpgとか

**Comment by karintou8710** [comment]
Base64で保存するのをやめるのも効果ありそう。
isarでバイナリ保存も可能みたいだから、それでもいいかも？
だね。最低限まで圧縮して良さそう。

**Comment by karintou8710** [comment]
flutterでも画像をファイルとして保存できるのか。

**Comment by toyoshin5** [comment]
バイナリ保存、ありだね
ファイル保存なら、ネイティブiOSアプリ開発だと各アプリに /document とか /library みたいな Flieアプリからはアクセスできない隠れたディレクトリが用意されていて、そこに保存はできるね。Flutterでもできるんじゃないかな。
