### ISSUE TITLE
実機でアプリを起動していると、発熱が強め

### ISSUE THREAD

**Issue by karintou8710** [toyoshin5/gohan_map#77]
パフォーマンス面で何か問題がありそう。
そこから調査・修正。

**Comment by toyoshin5** [comment]
iPhone6Sだと、モーダルが2枚重ねて出てくるとちょっと重い。
タイムラインモーダルの上に出てくる投稿画面など。

**Comment by toyoshin5** [comment]
ちなみにReleaseModeでも熱い？

**Comment by karintou8710** [comment]
ワイのiPhone13もモーダル２枚の場面、重たくなるわ。
ReleaseModeでもじんわりと熱いね。どの画面でも共通して熱いと思う。

**Comment by toyoshin5** [comment]
6Sだから重いのは致し方ないとおもってたけど、熱くなるのは改善したいなあ〜〜

**Comment by toyoshin5** [comment]
120HzのAndroid実機で60fpsしか出ていない問題を確認
パフォーマンスの問題なのかは不明

**Comment by toyoshin5** [comment]
https://cdn.discordapp.com/attachments/1047895851923677206/1157922450215010395/Screenshot_20231001-150939.png?ex=651a5ed1&is=65190d51&hm=abce09215d4ca88e2217bb73f51c4e90774c683d9a78208936fae4cbe9379da5&

**Comment by toyoshin5** [comment]
自分の環境ではFlutterアプリは60fpsまでしか出ないらしい
この端末だけかAndroid全部かは不明だけど、とりあえず本発熱問題とは無関係

**Comment by karintou8710** [comment]
他のアプリだと120Hz出るのか気になるね

**Comment by toyoshin5** [comment]
この60fpsしか出ない問題、Android×Flutterで発生する不具合？だったらしくて、外部パッケージで解決できた。
