### ISSUE TITLE
機種変更の際にデータ移行を可能に

### ISSUE THREAD

**Issue by karintou8710** [toyoshin5/gohan_map#80]

**Comment by toyoshin5** [comment]
## 機種変更時にデータ移行するだけ場合
 - DBと画像ファイルをzip圧縮して読み書き
 
## 複数端末でデータを同期したい場合
- DB更新時にDBと画像ファイルをzip圧縮してGoogleDriveかiCloudDrive書きだし？
- 起動時にGoogleDriveかiCloudDriveを見に行く？

**Comment by toyoshin5** [comment]
実装重そうなので、初回リリースには含めないとする
