### ISSUE TITLE
検索切り替えのデザイン

### ISSUE THREAD

**Issue by toyoshin5** [toyoshin5/gohan_map#81]
SegmentControlのデザイン

現状はAndroid(左)風
iOS風(右) も良いと思うんだけどいかが？

<img width="513" alt="スクリーンショット 2023-08-13 14 15 38" src="https://github.com/toyoshin5/gohan_map/assets/43494392/aed00160-96ee-4f1b-8136-024e7c8f55a0">

<img width="467" alt="スクリーンショット 2023-08-13 14 13 24" src="https://github.com/toyoshin5/gohan_map/assets/43494392/6d2f5004-4786-439d-a3c0-6ec2220170d9">

**Comment by karintou8710** [comment]
IOS風デザインの方、現在のページがはっきり見えていいと思う！
