### ISSUE TITLE
色をなんとかする

### ISSUE THREAD

**Issue by toyoshin5** [toyoshin5/gohan_map#83]
現状だとスプラッシュの青と
マップ右下のボタンの青と
日付選択の青と
住所アイコンの青が揃っていない

アプリのテーマカラーを決めていきたい

**Comment by karintou8710** [comment]
たしかに（ごめん、割と適当に色決めてた）

**Comment by toyoshin5** [comment]
いえいえ私も色はワカラナイ..

**Comment by toyoshin5** [comment]
デザインを大きく変更するのでその時対応
