### ISSUE TITLE
【相談】iOSのUIを使うかAndroidのUIを使うか独自UIで行くか

### ISSUE THREAD

**Issue by toyoshin5** [toyoshin5/gohan_map#88]
<img width="538" alt="スクリーンショット 2023-08-14 16 51 34" src="https://github.com/toyoshin5/gohan_map/assets/43494392/8586cfc1-cd2c-424c-b069-0bce1de665b5">
<img width="538" alt="スクリーンショット 2023-08-14 16 52 12" src="https://github.com/toyoshin5/gohan_map/assets/43494392/a00d4cde-439b-4c98-a291-b7a02cc2e9a4">

現状、アクションシートやメニューでiOSネイティブのUIをところどころ採用しているが、
アプリのUIがそこまでApple製アプリ風ではないので、変えてもいいのではというあるみかんの意見

調査した限りだとiOSのメニューを採用しているのはTwitter,メルカリApple製アプリ
独自のメニューを採用しているのはDiscord,Instagram
Android風のメニューを採用しているのは Google製アプリ

TwitterとメルカリはApple風のUIしてないけどメニューはネイティブのUIなので結構好みの問題

Twitter
![image](https://github.com/toyoshin5/gohan_map/assets/43494392/bea3c862-52cb-4151-8b79-065ab357afcc)
Discord
![image](https://github.com/toyoshin5/gohan_map/assets/43494392/5b5ed3db-8bfa-4d24-8b1a-fbbf27c132a9)
GoogleMap
![image](https://github.com/toyoshin5/gohan_map/assets/43494392/d2c072d2-d447-45d1-a136-e724169ebb35)

**Comment by karintou8710** [comment]
確かに、IOS風のメニュー画面である必要はなさそう。
今後のデザインに合うように変えていこ
