### ISSUE TITLE
ピンが増えてくると選択時に挙動がバグる

### ISSUE THREAD

**Issue by karintou8710** [toyoshin5/gohan_map#98]
ピンを選択時に、選択した以外のピンが一瞬フォーカスされてアニメーションがおかしくなることが頻繁にある。

**Comment by toyoshin5** [comment]
これ原因は不明だけど、発生条件はなんとなくわかるんよね。
ピンをタップしてマップが自動スクロールするとき、画面上のいずれかのピンが画面外(画面上部？)に消えるとアニメーションがバグるように見える。
